export const CONFIG = {
  FILE_URL:
    "https://canvas.samsungvx.com/organizations/23599CF5-F41D-471A-97F1-6F3872F2A44C/partners/D3B51B78-81FA-4A0F-834A-2AE311ECCDD4/widget/flights.json",
  OPENWEATHER_API_KEY: "d34469173c876dc3e734f40f63a5aa5c",
  OPENWEATHER_URL:
    "https://api.openweathermap.org/data/2.5/weather?units=metric&lang=pl&q=",
  // ARRIVAL_FILE_URL: "https://canvas.samsungvx.com/organizations/23599CF5-F41D-471A-97F1-6F3872F2A44C/partners/F4A4F3BE-182C-4A0F-AEFB-A9A3F66E62E6/widget/flights.json",
  AIRLINE_ICON_BASE_URL:
    "https://canvas.samsungvx.com/organizations/23599CF5-F41D-471A-97F1-6F3872F2A44C/partners/D3B51B78-81FA-4A0F-834A-2AE311ECCDD4/widget/icons/",
  AVIATIONSTACK_API_KEY: "672e46b6f7085eeec91f671df39a7467", // <-- Add this line
  AVIATIONSTACK_BASE_URL: "https://api.aviationstack.com/v1/timetable",
  WEATHER_CACHE_TTL: 3600000,
  DATA_REFRESH_INTERVAL: 120000,  
  WEATHER_REFRESH_INTERVAL: 600000,
};

export const IATA_TO_CITY_MAPPING = {
  WAW: "WARSAW",
  BCN: "BARCELONA",
  BER: "BERLIN",
  KE: "NAIROBI",
  DEL: "DELHI",
};

export const IATA_CITY_MAPPING = [
  { iata: "WAW", city: "Warsaw" },
  { iata: "JFK", city: "New York" },
  { iata: "LHR", city: "London" },
  { iata: "CDG", city: "Paris" },
  { iata: "FRA", city: "Frankfurt" },
  { iata: "DXB", city: "Dubai" },
  { iata: "HND", city: "Tokyo" },
  { iata: "SIN", city: "Singapore" },
  { iata: "SYD", city: "Sydney" },
  { iata: "PEK", city: "Beijing" },
  { iata: "DOH", city: "Doha" },
  { iata: "BEG", city: "Belgrade" },
  { iata: "BUD", city: "Budapest" },
  { iata: "ALC", city: "Alicante" },
  { iata: "ATH", city: "Athens" },
  { iata: "BRU", city: "Brussels" },
  { iata: "AMS", city: "Amsterdam" },
  { iata: "ZRH", city: "Zurich" },
  { iata: "CPH", city: "Copenhagen" },
  { iata: "CTA", city: "Catania" },
  { iata: "AYT", city: "Antalya" },
  { iata: "BER", city: "Berlin" },
  { iata: "CXR", city: "Nha Trang" },
  { iata: "BCN", city: "Barcelona" },
  { iata: "BOM", city: "Mumbai" },
  { iata: "ARN", city: "Stockholm" },
  { iata: "BLL", city: "Billund" },
  { iata: "CAI", city: "Cairo" },
  { iata: "DWC", city: "Dubai" },
  { iata: "CGN", city: "Cologne" },
  { iata: "SVO", city: "Moscow" },
  { iata: "IST", city: "Istanbul" },
  { iata: "MUC", city: "Munich" },
  { iata: "MAD", city: "Madrid" },
  { iata: "ORD", city: "Chicago" },
  { iata: "LAX", city: "Los Angeles" },
  { iata: "YYZ", city: "Toronto" },
  { iata: "GRU", city: "São Paulo" },
  { iata: "JNB", city: "Johannesburg" },
  { iata: "ICN", city: "Seoul" },
  { iata: "DEL", city: "Delhi" },
  { iata: "MEX", city: "Mexico City" },
  { iata: "BKK", city: "Bangkok" },
  { iata: "SYD", city: "Sydney" },
  { iata: "SFO", city: "San Francisco" },
  { iata: "MIA", city: "Miami" },
  { iata: "VIE", city: "Vienna" },
  { iata: "OSL", city: "Oslo" },
  { iata: "HEL", city: "Helsinki" },
  { iata: "DUB", city: "Dublin" },
  { iata: "PRG", city: "Prague" },
  { iata: "LIS", city: "Lisbon" },
  { iata: "CPH", city: "Copenhagen" },
  { iata: "ZAG", city: "Zagreb" },
  { iata: "RIX", city: "Riga" },
  { iata: "TLL", city: "Tallinn" },
  { iata: "VNO", city: "Vilnius" },
  { iata: "CUN", city: "Cancún" },
  { iata: "BSL", city: "Basel" },
  { iata: "AGP", city: "Malaga" },
  { iata: "BRI", city: "Bari" },
];

export const STATUS_OPTIONS = ["On Time", "Boarding", "Delayed", "Cancelled"];
export const STATUS_CLASSES = ["on-time", "boarding", "delayed", "cancelled"];
